FROM cdrx/pyinstaller-windows:latest

COPY requirements.txt /src/
RUN pip install -r requirements.txt

COPY main.py /src/
RUN pyinstaller --onefile --name token-agent main.py

CMD ["cp", "/src/dist/token-agent.exe", "/output/"]
