"""Initial migration

Revision ID: 410c29d85d8c
Revises: 
Create Date: 2026-05-14 12:29:44.905068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410c29d85d8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('response_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('protocol_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vri_id', sa.String(length=50), nullable=False),
    sa.Column('org_title', sa.String(length=255), nullable=False),
    sa.Column('mit_number', sa.String(length=100), nullable=True),
    sa.Column('mit_title', sa.Text(), nullable=True),
    sa.Column('mi_number', sa.String(length=100), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('valid_date', sa.Date(), nullable=True),
    sa.Column('result_docnum', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('verifier', sa.String(length=255), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vri_id')
    )
    op.create_table('check_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('total_calibrations', sa.Integer(), nullable=False),
    sa.Column('total_protocols', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('warnings_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocol_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('protocol_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_file_id', sa.Integer(), nullable=False),
    sa.Column('protocol_number', sa.String(length=100), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('mit_number', sa.String(length=100), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('verifier', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('pressure_units', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('verification_method', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_file_id'], ['protocol_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_run_id', sa.Integer(), nullable=False),
    sa.Column('calibration_id', sa.Integer(), nullable=True),
    sa.Column('protocol_data_id', sa.Integer(), nullable=True),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calibration_id'], ['calibrations.id'], ),
    sa.ForeignKeyConstraint(['check_run_id'], ['check_runs.id'], ),
    sa.ForeignKeyConstraint(['protocol_data_id'], ['protocol_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_results')
    op.drop_table('protocol_data')
    op.drop_table('users')
    op.drop_table('protocol_files')
    op.drop_table('check_runs')
    op.drop_table('calibrations')
    op.drop_table('ai_requests')
    # ### end Alembic commands ###
